name: helloWorldWorkflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hellothere
        run: echo "Hello there"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: generalKenobi
        run: echo "General Kenobi"
        shell: bash

